/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "IntInt.h"

bool_t
xdr_MyInt (XDR *xdrs, MyInt *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->my_int))
		 return FALSE;
	return TRUE;
}
