/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "IntInt.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct MyInt *
testint_1(struct MyInt *argp, CLIENT *clnt)
{
	static struct MyInt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, TestInt,
		(xdrproc_t) xdr_MyInt, (caddr_t) argp,
		(xdrproc_t) xdr_MyInt, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
