/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTINT_H_RPCGEN
#define _INTINT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct MyInt {
	int my_int;
};
typedef struct MyInt MyInt;

#define INTINTPROG 55555
#define INTINTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TestInt 1
extern  struct MyInt * testint_1(struct MyInt *, CLIENT *);
extern  struct MyInt * testint_1_svc(struct MyInt *, struct svc_req *);
extern int intintprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TestInt 1
extern  struct MyInt * testint_1();
extern  struct MyInt * testint_1_svc();
extern int intintprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_MyInt (XDR *, MyInt*);

#else /* K&R C */
extern bool_t xdr_MyInt ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTINT_H_RPCGEN */
