// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntInt.proto

#include "IntInt.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace intint {
class MyIntDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MyInt>
      _instance;
} _MyInt_default_instance_;
}  // namespace intint
namespace protobuf_IntInt_2eproto {
static void InitDefaultsMyInt() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::intint::_MyInt_default_instance_;
    new (ptr) ::intint::MyInt();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::intint::MyInt::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MyInt =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMyInt}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_MyInt.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::intint::MyInt, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::intint::MyInt, my_int_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::intint::MyInt)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::intint::_MyInt_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "IntInt.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014IntInt.proto\022\006intint\"\027\n\005MyInt\022\016\n\006my_in"
      "t\030\001 \001(\00328\n\013IntegerTest\022)\n\007SendInt\022\r.inti"
      "nt.MyInt\032\r.intint.MyInt\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 113);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "IntInt.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_IntInt_2eproto
namespace intint {

// ===================================================================

void MyInt::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MyInt::kMyIntFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MyInt::MyInt()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_IntInt_2eproto::scc_info_MyInt.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:intint.MyInt)
}
MyInt::MyInt(const MyInt& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  my_int_ = from.my_int_;
  // @@protoc_insertion_point(copy_constructor:intint.MyInt)
}

void MyInt::SharedCtor() {
  my_int_ = GOOGLE_LONGLONG(0);
}

MyInt::~MyInt() {
  // @@protoc_insertion_point(destructor:intint.MyInt)
  SharedDtor();
}

void MyInt::SharedDtor() {
}

void MyInt::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MyInt::descriptor() {
  ::protobuf_IntInt_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_IntInt_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MyInt& MyInt::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_IntInt_2eproto::scc_info_MyInt.base);
  return *internal_default_instance();
}


void MyInt::Clear() {
// @@protoc_insertion_point(message_clear_start:intint.MyInt)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  my_int_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool MyInt::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:intint.MyInt)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 my_int = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &my_int_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:intint.MyInt)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:intint.MyInt)
  return false;
#undef DO_
}

void MyInt::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:intint.MyInt)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 my_int = 1;
  if (this->my_int() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->my_int(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:intint.MyInt)
}

::google::protobuf::uint8* MyInt::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:intint.MyInt)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 my_int = 1;
  if (this->my_int() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->my_int(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:intint.MyInt)
  return target;
}

size_t MyInt::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:intint.MyInt)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int64 my_int = 1;
  if (this->my_int() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->my_int());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MyInt::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:intint.MyInt)
  GOOGLE_DCHECK_NE(&from, this);
  const MyInt* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MyInt>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:intint.MyInt)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:intint.MyInt)
    MergeFrom(*source);
  }
}

void MyInt::MergeFrom(const MyInt& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:intint.MyInt)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.my_int() != 0) {
    set_my_int(from.my_int());
  }
}

void MyInt::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:intint.MyInt)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MyInt::CopyFrom(const MyInt& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:intint.MyInt)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MyInt::IsInitialized() const {
  return true;
}

void MyInt::Swap(MyInt* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MyInt::InternalSwap(MyInt* other) {
  using std::swap;
  swap(my_int_, other->my_int_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MyInt::GetMetadata() const {
  protobuf_IntInt_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_IntInt_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace intint
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::intint::MyInt* Arena::CreateMaybeMessage< ::intint::MyInt >(Arena* arena) {
  return Arena::CreateInternal< ::intint::MyInt >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
