// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntInt.proto

#ifndef PROTOBUF_INCLUDED_IntInt_2eproto
#define PROTOBUF_INCLUDED_IntInt_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_IntInt_2eproto 

namespace protobuf_IntInt_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_IntInt_2eproto
namespace intint {
class MyInt;
class MyIntDefaultTypeInternal;
extern MyIntDefaultTypeInternal _MyInt_default_instance_;
}  // namespace intint
namespace google {
namespace protobuf {
template<> ::intint::MyInt* Arena::CreateMaybeMessage<::intint::MyInt>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace intint {

// ===================================================================

class MyInt : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:intint.MyInt) */ {
 public:
  MyInt();
  virtual ~MyInt();

  MyInt(const MyInt& from);

  inline MyInt& operator=(const MyInt& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MyInt(MyInt&& from) noexcept
    : MyInt() {
    *this = ::std::move(from);
  }

  inline MyInt& operator=(MyInt&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MyInt& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MyInt* internal_default_instance() {
    return reinterpret_cast<const MyInt*>(
               &_MyInt_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MyInt* other);
  friend void swap(MyInt& a, MyInt& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MyInt* New() const final {
    return CreateMaybeMessage<MyInt>(NULL);
  }

  MyInt* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MyInt>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MyInt& from);
  void MergeFrom(const MyInt& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MyInt* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 my_int = 1;
  void clear_my_int();
  static const int kMyIntFieldNumber = 1;
  ::google::protobuf::int64 my_int() const;
  void set_my_int(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:intint.MyInt)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 my_int_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_IntInt_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MyInt

// int64 my_int = 1;
inline void MyInt::clear_my_int() {
  my_int_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MyInt::my_int() const {
  // @@protoc_insertion_point(field_get:intint.MyInt.my_int)
  return my_int_;
}
inline void MyInt::set_my_int(::google::protobuf::int64 value) {
  
  my_int_ = value;
  // @@protoc_insertion_point(field_set:intint.MyInt.my_int)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace intint

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_IntInt_2eproto
